# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eMMKAJ1nQqAaNIdxyrMqlqz_m4XIUTw
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

def encode_one_hot(data_frame, frame_column:str):
  '''
  Получаем на вход дата фрейм и столбец
  Ищем количество строк в столбец
  Ищем уникальные значения внутри столбца
  В цикле идем по уникальным значениям:
    - формируем список значений, где ставится единица, в случае совпадения
    наименования столбца и значения в кодируемом столбце. В противном случае 0
    1*True==1; 1*False==0
    - добавляем столбец с уникальным именем в конец датафрейма, в качестве
    значений берем полученный список
    - отправляемся на следующую итерацию
  Возвращаем датафрейм.
  '''
  rows_number = data_frame.shape[0]
  new_columns = data_frame[frame_column].unique()
  for i in range(len(new_columns)):
    col = [1 * (data_frame[frame_column].loc[data_frame.index[k]] == new_columns[i]) for k in range(rows_number)]
    data_frame.loc[:, new_columns[i]] = col
  # data_frame = data_frame.drop([frame_column], axis=1) - удалит стоблец, оставил для наглядности
  return data_frame


data_new = encode_one_hot(data, 'whoAmI')
data_new.head(20)